### ISSUE TITLE
CI Does Not Build with Uppercase Chars in $GITHUB_REPOSITORY variable

### ISSUE THREAD

**Issue by WayneLambert** [testdrivenio/django-github-digitalocean#3]
For anyone that has either a username or a repository name in GitHub that contains capital letters, the build job will fail. For example, my username is `WayneLambert`, therefore my build process failed with the following in the traceback:

```log
Run docker-compose -f docker-compose.ci.yml build
  docker-compose -f docker-compose.ci.yml build
  shell: /bin/bash -e {0}
  env:
    WEB_IMAGE: docker.pkg.github.com/WayneLambert/django-github-digitalocean/web
    NGINX_IMAGE: docker.pkg.github.com/WayneLambert/django-github-digitalocean/nginx
Building web
invalid reference format: repository name must be lowercase
##[error]Process completed with exit code 1.
```
Full image below:

![ci-failure](https://user-images.githubusercontent.com/44729076/89336734-c2801f80-d691-11ea-95bd-bfc31dfb910e.png)

By the look of things, the variable takes the repository name as a concatenation of the username and the repository name exactly as it is.

**Comment by pattoM** [comment]
I circumvented the unnecessary variable by just hardcoding the actual url. In my case, my github username is pattoM and the capitalized m was bringing on issues.

**Comment by WayneLambert** [comment]
Yes, you can hard code the value and it will then build but if your goal is to build a template for future projects, then you can replace `$GITHUB_REPOSITORY` with `$(echo $GITHUB_REPOSITORY | tr '[:upper:]' '[:lower:]')` and it will build.
