### ISSUE TITLE
Deploy Step: Build and deploy images on DigitalOcean [Query]

### ISSUE THREAD

**Issue by WayneLambert** [testdrivenio/django-github-digitalocean#5]
I assume the `-p` flag in the docker login command within the `main.yml` file is the password. Shouldn't that also be an environment variable?

https://github.com/testdrivenio/django-github-digitalocean/blob/5a1801732b869e3e50f124b192d48f0d4a7bf34b/.github/workflows/main.yml#L85

**Comment by mjhea0** [comment]
Yes, I will make that change next time I update the post. Thanks!

**Comment by mjhea0** [comment]
Updated.
