### ISSUE TITLE
No such file or directory

### ISSUE THREAD

**Issue by Sjk-Lacoste** [testdrivenio/django-github-digitalocean#6]
My builds pass but for some reason when it runs deploy job I get this error: `scp: /app: No such file or directory`

**Comment by banagale** [comment]
@Sjk-Lacoste This is happening in your deploy section of main. It is trying to copy into a folder on your DO instance.

If it does not exist, you maybe accidentally skipped this step from [the guide](https://testdriven.io/blog/deploying-django-to-digitalocean-with-docker-and-github-actions/):

> Then, create a new directory for the app:
> 
> `$ ssh -o StrictHostKeyChecking=no root@<YOUR_INSTANCE_IP> mkdir /app`
