### ISSUE TITLE
Use of set-env has been disabled in Github Actions

### ISSUE THREAD

**Issue by quinceleaf** [testdrivenio/django-github-digitalocean#9]
[Just a note: I'm working through using the tutorial/adapting it for my own project and have run into the following issue. As I work through the issue and make the necessary changes for my own project, I'll update this issue with suggested fix(es).]

The use of `set-env` in Github Actions has been disabled (see [GitHub Actions: Deprecating set-env and add-path commands](https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/))

Running as currently available in `/.github/workflows/main.yml` throws

```
Error: The `set-env` command is disabled. Please upgrade to 
using Environment Files  or opt into unsecure command execution 
by setting the `ACTIONS_ALLOW_UNSECURE_COMMANDS` 
environment variable to `true`. 
```

**Comment by mjhea0** [comment]
Updated
